=== Kalapaja/clear-signing/schemas/contractlist.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/nailkhaf/clear-signing/main/schema/contract-list.schema.json",
  "title": "Clear Signing Contract List",
  "description": "Schema for lists of contracts compatible with Clear Signing",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [
        {
          "major": 1,
          "minor": 0,
          "patch": 0
        }
      ],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when contracts are removed from the list or contract addresses are changed.",
          "minimum": 0,
          "examples": [1, 2]
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when contracts are added to the list.",
          "minimum": 0,
          "examples": [0, 1]
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0,
          "examples": [0, 1]
        }
      },
      "required": ["major", "minor", "patch"]
    },
    "TagIdentifier": {
      "type": "string",
      "description": "The unique identifier of a tag",
      "minLength": 1,
      "maxLength": 10,
      "pattern": "^[\\w]+$",
      "examples": ["defi", "dao"]
    },
    "TagDefinition": {
      "type": "object",
      "description": "Definition of a tag that can be associated with a contract via its identifier",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the tag",
          "pattern": "^[ \\w]+$",
          "minLength": 1,
          "maxLength": 20
        },
        "description": {
          "type": "string",
          "description": "A user-friendly description of the tag",
          "pattern": "^[ \\w\\.,:]+$",
          "minLength": 1,
          "maxLength": 200
        }
      },
      "required": ["name", "description"],
      "examples": [
        {
          "name": "DeFi",
          "description": "Decentralized Finance protocols"
        }
      ]
    },
    "ContractInfo": {
      "type": "object",
      "description": "Metadata for a single contract in a contract list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the network where this contract is deployed",
          "minimum": 1,
          "examples": [1, 42]
        },
        "address": {
          "type": "string",
          "description": "The checksummed address of the contract on the specified chain ID",
          "pattern": "^0x[a-fA-F0-9]{40}$",
          "examples": [
            "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
          ]
        },
        "name": {
          "type": "string",
          "description": "The name of the contract",
          "minLength": 1,
          "maxLength": 60,
          "pattern": "^[ \\S]+$",
          "examples": ["Uniswap V2 Router"]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the contract logo asset",
          "format": "uri",
          "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
        },
        "tags": {
          "type": "array",
          "description": "An array of tag identifiers associated with the contract; tags are defined at the list level",
          "items": {
            "$ref": "#/definitions/TagIdentifier"
          },
          "maxItems": 10,
          "examples": ["defi"]
        }
      },
      "required": ["chainId", "address", "name"]
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the contract list",
      "minLength": 1,
      "maxLength": 30,
      "pattern": "^[\\w \\.\\-]+$",
      "examples": ["My Contract List"]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "contracts": {
      "type": "array",
      "description": "The list of contracts included in the list",
      "items": {
        "$ref": "#/definitions/ContractInfo"
      },
      "minItems": 1,
      "maxItems": 10000
    },
    "keywords": {
      "type": "array",
      "description": "Keywords associated with the contents of the list; may be used in list discoverability",
      "items": {
        "type": "string",
        "description": "A keyword to describe the contents of the list",
        "minLength": 1,
        "maxLength": 20,
        "pattern": "^[\\w ]+$"
      },
      "maxItems": 20,
      "uniqueItems": true,
      "examples": ["DeFi", "DEX"]
    },
    "tags": {
      "type": "object",
      "description": "A mapping of tag identifiers to their definitions",
      "propertyNames": {
        "$ref": "#/definitions/TagIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/TagDefinition"
      },
      "maxProperties": 20,
      "examples": [
        {
          "stablecoin": {
            "name": "Stablecoin",
            "description": "A token with value pegged to another asset"
          }
        }
      ]
    },
    "logoURI": {
      "type": "string",
      "description": "A URI for the logo of the token list; suggest SVG or PNG of size 256x256",
      "format": "uri",
      "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
    }
  },
  "required": ["name", "timestamp", "version", "contracts"]
}

=== Kalapaja/clear-signing/examples/token/contractlist.json
{
  "$schema": "../../schemas/contractlist.schema.json",
  "name": "Local Contracts",
  "timestamp": "2026-01-10T14:50:00Z",
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  },
  "contracts": [
    {
      "chainId": 1,
      "address": "0x0000000000000000000000000000000000000001",
      "name": "User 1"
    },
    {
      "chainId": 1,
      "address": "0x0000000000000000000000000000000000001234",
      "name": "User 2"
    }
  ]
}

=== Kalapaja/clear-signing/examples/1inch/contractlist.json
{
  "$schema": "../../schemas/contractlist.schema.json",
  "name": "Local Contracts",
  "timestamp": "2026-01-10T14:50:00Z",
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  },
  "contracts": [
    {
      "chainId": 1,
      "address": "0x111111125421cA6dc452d289314280a0f8842A65",
      "name": "1inch: Aggregation Router V6"
    }, {
      "chainId": 1,
      "address": "0xeDD53Bf3feFA7c481E9f5eFD3af56152db8016D8",
      "name": "User wallet"
    }
  ]
}

=== Kalapaja/clear-signing/examples/clearcall/contractlist.json
{
  "$schema": "../../schemas/contractlist.schema.json",
  "name": "ERC20 Contracts",
  "timestamp": "2026-01-10T14:50:00Z",
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  },
  "contracts": [
    {
      "chainId": 31337,
      "address": "0xec5ab17cc35221cdf54eaeb0868ea82d4d75d9bf",
      "name": "Clear Call Router"
    },
    {
      "chainId": 31337,
      "address": "0x056451BBCEbbb1A764b52A7FB1E90Ac07536daC5",
      "name": "User 1"
    }
  ]
}

=== Kalapaja/clear-signing/examples/uniswap/contractlist.json
{
  "$schema": "../../schemas/contractlist.schema.json",
  "name": "Uniswap Contracts",
  "timestamp": "2026-01-10T14:50:00Z",
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  },
  "contracts": [
    {
      "chainId": 1,
      "address": "0x66a9893cC07D91D95644AEDD05D03f95e1dBA8Af",
      "name": "Uniswap V4: Universal Router"
    },
    {
      "chainId": 1,
      "address": "0x63B616328343C80Bfcc134658e44B1Fa7B883b49",
      "name": "User"
    },
    {
      "chainId": 1,
      "address": "0xEB3CBBD933E1E405221E5865a857531073b7e9C7",
      "name": "User"
    }
  ]
}
